Transform: AWS::Serverless-2016-10-31
Parameters:
  CertificateArn:
    Type: String
  DomainName:
    Type: String
  HostedZoneId:
    Type: String
Globals:
  HttpApi:
    Domain:
      CertificateArn:
        Ref: CertificateArn
      DomainName:
        Ref: DomainName
      Route53:
        HostedZoneId:
          Ref: HostedZoneId
Resources:
  Redirect:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: redirect.handler
      Runtime: nodejs12.x
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
  Schema:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: schema.handler
      Runtime: nodejs12.x
      Timeout: 15
      MemorySize: 320
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /schema
            Method: GET
